version: '3'
services:
  www:
    image: gemini-html-server:nightly-alpine
    restart: unless-stopped
    ports:
      - '8080:8080/tcp'
    volumes:
      - ./example/content:/data/content:ro
      - ./example/template.html:/usr/local/template.html:ro
    environment:
      # - CONTENT_PATH=/data/content
      - GEMINI_ROOT_URL=gemini://kelgors.me
